Repository JohnDamilola/URL-Shortener-2.0, pull requests merged in 2022-11, with the labels that each got.

#6 Fix Heroku deployment and Postgresql Migrations Update
  .gitignore
  backend/.env
  backend/Procfile
  backend/README.md
  backend/migrations/README
  backend/migrations/alembic.ini
  backend/migrations/env.py
  backend/migrations/script.py.mako
  backend/migrations/versions/ca5354b4cc9e_initial_migration.py
  backend/requirements.txt
  backend/src/__init__.py
  backend/src/app.py
  backend/src/config.py
  backend/src/extensions.py
  backend/src/models/__init__.py
  backend/src/models/user.py
  backend/src/routes/__init__.py
  backend/src/routes/auth.py
Labels: bug

#11 Implement homepage
  frontend/.firebase/hosting.YnVpbGQ.cache
  frontend/.firebaserc
  frontend/firebase.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/assets/images/mh.svg
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/Navbar/styles.scss
  frontend/src/index.css
  frontend/src/index.scss
  frontend/src/index.tsx
  frontend/src/screens/Home/index.tsx
  frontend/src/screens/Home/styles.scss
  frontend/yarn.lock
Labels: good first issue

#15 Added user management,i.e, user updation and deletion
  backend/src/routes/auth.py
Labels: good first issue

#18 16 edit and delete user account frontend
  frontend/src/components/Navbar/index.tsx
  frontend/src/routes.tsx
  frontend/src/screens/DashboardScreens/Dashboard.tsx
  frontend/src/screens/DashboardScreens/EditUser.tsx
  frontend/src/screens/DashboardScreens/styles.scss
Labels: good first issue

#20 Implement overview page
  frontend/public/index.html
  frontend/src/components/DashboardNavbar/index.tsx
  frontend/src/components/DashboardNavbar/styles.scss
  frontend/src/components/Navbar/styles.scss
  frontend/src/components/Sidebar/index.tsx
  frontend/src/components/Sidebar/styles.scss
  frontend/src/routes.tsx
  frontend/src/screens/DashboardScreens/Dashboard.tsx
  frontend/src/screens/DashboardScreens/styles.scss
Labels: good first issue

#23 Update links.py
  backend/src/routes/links.py
Labels: enhancement

#21 17 fix backend tests
  .github/workflows/Application.yml
  .github/workflows/test.yml
  backend/.env
  backend/src/app.py
  backend/src/config.py
  backend/src/models/links.py
  backend/src/models/user.py
  backend/src/routes/auth.py
  backend/src/routes/links.py
  backend/test/requirements.txt
  backend/test/test_app.py
  backend/test/test_auth.py
  backend/test/test_model.py
  backend/test/test_shorten_links.py
  backend/test/test_urls.py
  backend/test/test_views.py
Labels: bug

#36 33 fix backend tests
  .github/workflows/Application.yml
  backend/src/models/links.py
  backend/src/routes/links.py
  backend/test/test.py
  backend/test/test_shorten_links.py
Labels: bug
